//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChannelName {
            get {
                return ((string)(this["ChannelName"]));
            }
            set {
                this["ChannelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoMessageEnabled {
            get {
                return ((bool)(this["isAutoMessageEnabled"]));
            }
            set {
                this["isAutoMessageEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string AutoSendTime {
            get {
                return ((string)(this["AutoSendTime"]));
            }
            set {
                this["AutoSendTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAutoTraderEnabled {
            get {
                return ((bool)(this["isAutoTraderEnabled"]));
            }
            set {
                this["isAutoTraderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderMuted {
            get {
                return ((bool)(this["isTraderMuted"]));
            }
            set {
                this["isTraderMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderPraporEnabled {
            get {
                return ((bool)(this["isTraderPraporEnabled"]));
            }
            set {
                this["isTraderPraporEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderTherapistEnabled {
            get {
                return ((bool)(this["isTraderTherapistEnabled"]));
            }
            set {
                this["isTraderTherapistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderPeacekeeperEnabled {
            get {
                return ((bool)(this["isTraderPeacekeeperEnabled"]));
            }
            set {
                this["isTraderPeacekeeperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderMechanicEnabled {
            get {
                return ((bool)(this["isTraderMechanicEnabled"]));
            }
            set {
                this["isTraderMechanicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderSkierEnabled {
            get {
                return ((bool)(this["isTraderSkierEnabled"]));
            }
            set {
                this["isTraderSkierEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderRagmanEnabled {
            get {
                return ((bool)(this["isTraderRagmanEnabled"]));
            }
            set {
                this["isTraderRagmanEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderFenceEnabled {
            get {
                return ((bool)(this["isTraderFenceEnabled"]));
            }
            set {
                this["isTraderFenceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderJaegerEnabled {
            get {
                return ((bool)(this["isTraderJaegerEnabled"]));
            }
            set {
                this["isTraderJaegerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderLightkeeperEnabled {
            get {
                return ((bool)(this["isTraderLightkeeperEnabled"]));
            }
            set {
                this["isTraderLightkeeperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTwitchTradersEnabled {
            get {
                return ((bool)(this["isTwitchTradersEnabled"]));
            }
            set {
                this["isTwitchTradersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTradersEnabled {
            get {
                return ((bool)(this["isTradersEnabled"]));
            }
            set {
                this["isTradersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isChatBonusEnabled {
            get {
                return ((bool)(this["isChatBonusEnabled"]));
            }
            set {
                this["isChatBonusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCommandsPaused {
            get {
                return ((bool)(this["isCommandsPaused"]));
            }
            set {
                this["isCommandsPaused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModBitsEnabled {
            get {
                return ((bool)(this["isModBitsEnabled"]));
            }
            set {
                this["isModBitsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModRefundEnabled {
            get {
                return ((bool)(this["isModRefundEnabled"]));
            }
            set {
                this["isModRefundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModWhitelistEnabled {
            get {
                return ((bool)(this["isModWhitelistEnabled"]));
            }
            set {
                this["isModWhitelistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBonusMultiplierEnabled {
            get {
                return ((bool)(this["isBonusMultiplierEnabled"]));
            }
            set {
                this["isBonusMultiplierEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSweatbotEnabled {
            get {
                return ((bool)(this["isSweatbotEnabled"]));
            }
            set {
                this["isSweatbotEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isUpdateCheckEnabled {
            get {
                return ((bool)(this["isUpdateCheckEnabled"]));
            }
            set {
                this["isUpdateCheckEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isDebugOn {
            get {
                return ((bool)(this["isDebugOn"]));
            }
            set {
                this["isDebugOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBitMsgEnabled {
            get {
                return ((bool)(this["isBitMsgEnabled"]));
            }
            set {
                this["isBitMsgEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isConfirmationDisabled {
            get {
                return ((bool)(this["isConfirmationDisabled"]));
            }
            set {
                this["isConfirmationDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderMenuEnabled {
            get {
                return ((bool)(this["isTraderMenuEnabled"]));
            }
            set {
                this["isTraderMenuEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isFollowBonusEnabled {
            get {
                return ((bool)(this["isFollowBonusEnabled"]));
            }
            set {
                this["isFollowBonusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSubBonusEnabled {
            get {
                return ((bool)(this["isSubBonusEnabled"]));
            }
            set {
                this["isSubBonusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBitCostEnabled {
            get {
                return ((bool)(this["isBitCostEnabled"]));
            }
            set {
                this["isBitCostEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isEconomyOn {
            get {
                return ((bool)(this["isEconomyOn"]));
            }
            set {
                this["isEconomyOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSendKeyEnabled {
            get {
                return ((bool)(this["isSendKeyEnabled"]));
            }
            set {
                this["isSendKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSubBonusMultiEnabled {
            get {
                return ((bool)(this["isSubBonusMultiEnabled"]));
            }
            set {
                this["isSubBonusMultiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModAddEnabled {
            get {
                return ((bool)(this["isModAddEnabled"]));
            }
            set {
                this["isModAddEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModRemoveEnabled {
            get {
                return ((bool)(this["isModRemoveEnabled"]));
            }
            set {
                this["isModRemoveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBitGambleEnabled {
            get {
                return ((bool)(this["isBitGambleEnabled"]));
            }
            set {
                this["isBitGambleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isblerpEnabled {
            get {
                return ((bool)(this["isblerpEnabled"]));
            }
            set {
                this["isblerpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSubOnlySweatbotCommand {
            get {
                return ((bool)(this["isSubOnlySweatbotCommand"]));
            }
            set {
                this["isSubOnlySweatbotCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSubOnlyGambleCommand {
            get {
                return ((bool)(this["isSubOnlyGambleCommand"]));
            }
            set {
                this["isSubOnlyGambleCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSubOnlyBotCommand {
            get {
                return ((bool)(this["isSubOnlyBotCommand"]));
            }
            set {
                this["isSubOnlyBotCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CustomCommands")]
        public string LastUsedProfile {
            get {
                return ((string)(this["LastUsedProfile"]));
            }
            set {
                this["LastUsedProfile"] = value;
            }
        }
    }
}
