//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGooseEnabled {
            get {
                return ((bool)(this["IsGooseEnabled"]));
            }
            set {
                this["IsGooseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChannelName {
            get {
                return ((string)(this["ChannelName"]));
            }
            set {
                this["ChannelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWiggleEnabled {
            get {
                return ((bool)(this["IsWiggleEnabled"]));
            }
            set {
                this["IsWiggleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsKeyEnabled {
            get {
                return ((bool)(this["IsKeyEnabled"]));
            }
            set {
                this["IsKeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDropEnabled {
            get {
                return ((bool)(this["IsDropEnabled"]));
            }
            set {
                this["IsDropEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTurnEnabled {
            get {
                return ((bool)(this["IsTurnEnabled"]));
            }
            set {
                this["IsTurnEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPopEnabled {
            get {
                return ((bool)(this["IsPopEnabled"]));
            }
            set {
                this["IsPopEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isNormalCommandsEnabled {
            get {
                return ((bool)(this["isNormalCommandsEnabled"]));
            }
            set {
                this["isNormalCommandsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAutoMessageEnabled {
            get {
                return ((bool)(this["isAutoMessageEnabled"]));
            }
            set {
                this["isAutoMessageEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string AutoSendTime {
            get {
                return ((string)(this["AutoSendTime"]));
            }
            set {
                this["AutoSendTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAutoTraderEnabled {
            get {
                return ((bool)(this["isAutoTraderEnabled"]));
            }
            set {
                this["isAutoTraderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderMuted {
            get {
                return ((bool)(this["isTraderMuted"]));
            }
            set {
                this["isTraderMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderPraporEnabled {
            get {
                return ((bool)(this["isTraderPraporEnabled"]));
            }
            set {
                this["isTraderPraporEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderTherapistEnabled {
            get {
                return ((bool)(this["isTraderTherapistEnabled"]));
            }
            set {
                this["isTraderTherapistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderPeacekeeperEnabled {
            get {
                return ((bool)(this["isTraderPeacekeeperEnabled"]));
            }
            set {
                this["isTraderPeacekeeperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderMechanicEnabled {
            get {
                return ((bool)(this["isTraderMechanicEnabled"]));
            }
            set {
                this["isTraderMechanicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderSkierEnabled {
            get {
                return ((bool)(this["isTraderSkierEnabled"]));
            }
            set {
                this["isTraderSkierEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderRagmanEnabled {
            get {
                return ((bool)(this["isTraderRagmanEnabled"]));
            }
            set {
                this["isTraderRagmanEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderFenceEnabled {
            get {
                return ((bool)(this["isTraderFenceEnabled"]));
            }
            set {
                this["isTraderFenceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderJaegerEnabled {
            get {
                return ((bool)(this["isTraderJaegerEnabled"]));
            }
            set {
                this["isTraderJaegerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTraderLightkeeperEnabled {
            get {
                return ((bool)(this["isTraderLightkeeperEnabled"]));
            }
            set {
                this["isTraderLightkeeperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isTwitchTradersEnabled {
            get {
                return ((bool)(this["isTwitchTradersEnabled"]));
            }
            set {
                this["isTwitchTradersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string keyToSend {
            get {
                return ((string)(this["keyToSend"]));
            }
            set {
                this["keyToSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isDropMagEnabled {
            get {
                return ((bool)(this["isDropMagEnabled"]));
            }
            set {
                this["isDropMagEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isDropBagEnabled {
            get {
                return ((bool)(this["isDropBagEnabled"]));
            }
            set {
                this["isDropBagEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTradersEnabled {
            get {
                return ((bool)(this["isTradersEnabled"]));
            }
            set {
                this["isTradersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isGrenadeTossEnabled {
            get {
                return ((bool)(this["isGrenadeTossEnabled"]));
            }
            set {
                this["isGrenadeTossEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCrouchEnabled {
            get {
                return ((bool)(this["isCrouchEnabled"]));
            }
            set {
                this["isCrouchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isMagDumpEnabled {
            get {
                return ((bool)(this["isMagDumpEnabled"]));
            }
            set {
                this["isMagDumpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isHoldAimEnabled {
            get {
                return ((bool)(this["isHoldAimEnabled"]));
            }
            set {
                this["isHoldAimEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isChatBonusEnabled {
            get {
                return ((bool)(this["isChatBonusEnabled"]));
            }
            set {
                this["isChatBonusEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCommandsPaused {
            get {
                return ((bool)(this["isCommandsPaused"]));
            }
            set {
                this["isCommandsPaused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isMagDump360Enabled {
            get {
                return ((bool)(this["isMagDump360Enabled"]));
            }
            set {
                this["isMagDump360Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isProneEnabled {
            get {
                return ((bool)(this["isProneEnabled"]));
            }
            set {
                this["isProneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isVoiceLineEnabled {
            get {
                return ((bool)(this["isVoiceLineEnabled"]));
            }
            set {
                this["isVoiceLineEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isReloadEnabled {
            get {
                return ((bool)(this["isReloadEnabled"]));
            }
            set {
                this["isReloadEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPraiseSunEnabled {
            get {
                return ((bool)(this["isPraiseSunEnabled"]));
            }
            set {
                this["isPraiseSunEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isTouchGrassEnabled {
            get {
                return ((bool)(this["isTouchGrassEnabled"]));
            }
            set {
                this["isTouchGrassEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModBitsEnabled {
            get {
                return ((bool)(this["isModBitsEnabled"]));
            }
            set {
                this["isModBitsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isKnifeOutEnabled {
            get {
                return ((bool)(this["isKnifeOutEnabled"]));
            }
            set {
                this["isKnifeOutEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isJumpEnabled {
            get {
                return ((bool)(this["isJumpEnabled"]));
            }
            set {
                this["isJumpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isMuteWindowsEnabled {
            get {
                return ((bool)(this["isMuteWindowsEnabled"]));
            }
            set {
                this["isMuteWindowsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isWalkEnabled {
            get {
                return ((bool)(this["isWalkEnabled"]));
            }
            set {
                this["isWalkEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isHotMicEnabled {
            get {
                return ((bool)(this["isHotMicEnabled"]));
            }
            set {
                this["isHotMicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isNormGrenadeEnabled {
            get {
                return ((bool)(this["isNormGrenadeEnabled"]));
            }
            set {
                this["isNormGrenadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isWeaponSwapEnabled {
            get {
                return ((bool)(this["isWeaponSwapEnabled"]));
            }
            set {
                this["isWeaponSwapEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isFireModeEnabled {
            get {
                return ((bool)(this["isFireModeEnabled"]));
            }
            set {
                this["isFireModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModRefundEnabled {
            get {
                return ((bool)(this["isModRefundEnabled"]));
            }
            set {
                this["isModRefundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isModWhitelistEnabled {
            get {
                return ((bool)(this["isModWhitelistEnabled"]));
            }
            set {
                this["isModWhitelistEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBonusMultiplierEnabled {
            get {
                return ((bool)(this["isBonusMultiplierEnabled"]));
            }
            set {
                this["isBonusMultiplierEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isAudclipEnabled {
            get {
                return ((bool)(this["isAudclipEnabled"]));
            }
            set {
                this["isAudclipEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isSweatbotEnabled {
            get {
                return ((bool)(this["isSweatbotEnabled"]));
            }
            set {
                this["isSweatbotEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isUpdateCheckEnabled {
            get {
                return ((bool)(this["isUpdateCheckEnabled"]));
            }
            set {
                this["isUpdateCheckEnabled"] = value;
            }
        }
    }
}
